import { StyleSheet } from 'react-native';
import { horizontalScale, moderateScale } from '../utils/scaling';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0b0c14',
  },
  scrollContent: {
    padding: horizontalScale(24),
    paddingTop: horizontalScale(10),
  },
  headerTitle: {
    fontSize: moderateScale(42),
    color: '#FFFFFF',
    fontFamily: 'Manrope_700Bold',
    marginBottom: horizontalScale(30),
  },
  sectionGroup: {
    marginBottom: horizontalScale(20),
  },
  sectionLabel: {
    fontSize: moderateScale(9),
    color: 'rgba(255,255,255,0.4)',
    letterSpacing: 2,
    marginBottom: horizontalScale(10),
    fontFamily: 'Inter_700Bold',
    marginLeft: horizontalScale(4),
  },
  inputCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1D1F',
    borderRadius: moderateScale(20),
    paddingHorizontal: horizontalScale(24),
    height: horizontalScale(64),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  inputIconCircle: {
    width: horizontalScale(44),
    height: horizontalScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: horizontalScale(16),
  },
  inputText: {
    flex: 1,
    color: 'rgba(255,255,255,0.6)',
    fontFamily: 'Inter_600SemiBold',
    fontSize: moderateScale(15),
  },
  actionCard: {
    flexDirection: 'row',
    backgroundColor: '#1C1D1F',
    borderRadius: moderateScale(24),
    paddingHorizontal: horizontalScale(24),
    minHeight: horizontalScale(68),
    paddingVertical: horizontalScale(12),
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: horizontalScale(20),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  actionCardExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginBottom: 0,
    borderBottomWidth: 0,
  },
  securityWrapper: {
    marginBottom: 0,
  },
  securityDropdown: {
    backgroundColor: '#1C1D1F',
    borderBottomLeftRadius: moderateScale(32),
    borderBottomRightRadius: moderateScale(32),
    padding: horizontalScale(20),
    paddingTop: horizontalScale(10),
    paddingBottom: horizontalScale(40),
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: 'rgba(255,255,255,0.03)',
    marginBottom: horizontalScale(20),
  },
  innerSectionGroup: {
    marginBottom: horizontalScale(16),
  },
  innerSectionLabel: {
    fontSize: moderateScale(8),
    color: 'rgba(255,255,255,0.3)',
    letterSpacing: 1.5,
    fontFamily: 'Inter_700Bold',
    marginBottom: horizontalScale(8),
    marginLeft: horizontalScale(4),
  },
  innerTextInput: {
    flex: 1,
    color: '#FFFFFF',
    fontFamily: 'Inter_500Medium',
    fontSize: moderateScale(14),
  },
  updatePasswordBtn: {
    height: horizontalScale(52),
    borderRadius: moderateScale(16),
    overflow: 'hidden',
    marginTop: horizontalScale(8),
  },
  updatePasswordGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  updatePasswordBtnText: {
    color: '#FFFFFF',
    fontFamily: 'Manrope_700Bold',
    fontSize: moderateScale(15),
  },
  actionCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconCircle: {
    width: horizontalScale(44),
    height: horizontalScale(44),
    borderRadius: moderateScale(22),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: horizontalScale(16),
  },
  actionCardTitle: {
    fontSize: moderateScale(16),
    color: '#FFFFFF',
    fontFamily: 'Inter_600SemiBold',
  },
  softCard: {
    backgroundColor: '#1C1D1F',
    borderRadius: moderateScale(24),
    paddingHorizontal: horizontalScale(24),
    minHeight: horizontalScale(64),
    paddingVertical: horizontalScale(12),
    justifyContent: 'center',
    marginBottom: horizontalScale(20),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  softCardTitle: {
    fontSize: moderateScale(20),
    color: '#FFFFFF',
    fontFamily: 'Manrope_700Bold',
    marginBottom: horizontalScale(12),
  },
  softCardTitleNoMargin: {
    fontSize: moderateScale(17),
    color: '#FFFFFF',
    fontFamily: 'Inter_600SemiBold',
  },
  softCardDescription: {
    fontSize: moderateScale(13),
    color: 'rgba(255,255,255,0.3)',
    lineHeight: moderateScale(18),
    fontFamily: 'Inter_400Regular',
    marginBottom: horizontalScale(24),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: horizontalScale(8),
  },
  timeTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: horizontalScale(2),
  },
  subTextActive: {
    fontSize: moderateScale(12),
    color: '#3b82f6',
    fontFamily: 'Inter_700Bold',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  timePickerBlur: {
    borderTopLeftRadius: moderateScale(36),
    borderTopRightRadius: moderateScale(36),
    overflow: 'hidden',
  },
  timePickerContent: {
    padding: horizontalScale(24),
    paddingBottom: horizontalScale(0),
    backgroundColor: 'rgba(15, 15, 17, 0.95)',
  },
  modalHandle: {
    width: horizontalScale(40),
    height: horizontalScale(4),
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: moderateScale(2),
    alignSelf: 'center',
    marginBottom: horizontalScale(24),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: horizontalScale(32),
  },
  modalLabel: {
    fontSize: moderateScale(10),
    color: 'rgba(255,255,255,0.3)',
    letterSpacing: 2,
    fontFamily: 'Inter_700Bold',
    marginBottom: horizontalScale(4),
  },
  modalTitleText: {
    fontSize: moderateScale(22),
    color: '#FFFFFF',
    fontFamily: 'Manrope_700Bold',
  },
  closeBtn: {
    width: horizontalScale(40),
    height: horizontalScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  timePickerColumns: {
    flexDirection: 'row',
    height: horizontalScale(220),
    marginBottom: horizontalScale(32),
    alignItems: 'center',
  },
  timeColumn: {
    flex: 1,
    height: '100%',
  },
  columnLabel: {
    fontSize: moderateScale(9),
    color: 'rgba(255,255,255,0.2)',
    fontFamily: 'Inter_700Bold',
    textAlign: 'center',
    marginBottom: horizontalScale(12),
    letterSpacing: 1,
  },
  timeSeparator: {
    paddingHorizontal: horizontalScale(10),
    paddingTop: horizontalScale(20),
  },
  separatorText: {
    fontSize: moderateScale(32),
    color: 'rgba(255,255,255,0.1)',
    fontFamily: 'Manrope_700Bold',
  },
  timeItem: {
    height: horizontalScale(50),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: moderateScale(12),
  },
  timeItemActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  timeItemText: {
    fontSize: moderateScale(20),
    color: 'rgba(255,255,255,0.3)',
    fontFamily: 'Inter_600SemiBold',
  },
  timeItemTextActive: {
    color: '#3b82f6',
    fontSize: moderateScale(26),
    fontFamily: 'Manrope_800ExtraBold',
  },
  saveTimeBtn: {
    height: horizontalScale(60),
    borderRadius: moderateScale(22),
    overflow: 'hidden',
    marginBottom: horizontalScale(20),
  },
  saveTimeGradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: horizontalScale(12),
  },
  saveTimeBtnText: {
    fontSize: moderateScale(17),
    color: '#FFFFFF',
    fontFamily: 'Manrope_700Bold',
  },
  subText: {
    fontSize: moderateScale(12),
    color: 'rgba(255,255,255,0.3)',
    fontFamily: 'Inter_400Regular',
    marginTop: horizontalScale(2),
  },
  currencySelector: {
    height: horizontalScale(56),
    borderRadius: moderateScale(28),
    backgroundColor: '#2C2C2E',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(24),
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  currencySelectorText: {
    fontSize: moderateScale(15),
    color: '#FFFFFF',
    fontFamily: 'Inter_600SemiBold',
  },
  segmentedToggle: {
    flexDirection: 'row',
    backgroundColor: '#2C2C2E',
    borderRadius: moderateScale(18),
    padding: horizontalScale(3),
    width: horizontalScale(100),
    height: horizontalScale(36),
  },
  toggleOption: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: moderateScale(15),
  },
  toggleOptionActive: {
    backgroundColor: '#3b82f6',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: horizontalScale(4) },
    shadowOpacity: 0.3,
    shadowRadius: moderateScale(8),
    elevation: 4,
  },
  toggleText: {
    fontSize: moderateScale(11),
    color: 'rgba(255,255,255,0.4)',
    fontFamily: 'Inter_700Bold',
  },
  toggleTextActive: {
    color: '#FFFFFF',
  },
  deleteAccountBtn: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderRadius: moderateScale(24),
    paddingVertical: horizontalScale(18),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    marginTop: horizontalScale(16),
  },
  deleteAccountText: {
    color: '#ef4444',
    fontFamily: 'Manrope_700Bold',
    fontSize: moderateScale(15),
    letterSpacing: 0.5,
  },
  footerLinks: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: horizontalScale(32),
    gap: horizontalScale(12),
  },
  footerLinkText: {
    fontFamily: 'Inter_500Medium',
    fontSize: moderateScale(13),
    color: 'rgba(255,255,255,0.3)',
    textDecorationLine: 'underline',
  },
  footerDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
});

export default styles;
